const { Book, Category, User } = require('./models');

const booksData = [
  {
    title: "Война и мир",
    author: "Лев Толстой",
    authorId: "tolstoy",
    genre: "Художественная литература",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 890,
    oldPrice: 1200,
    rating: 5,
    reviewsCount: 1,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 1225,
    isbn: "978-5-04-098651-2",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040986512-L.jpg",
    description: "Роман-эпопея Льва Толстого, одно из величайших произведений русской литературы."
  },
  {
    title: "Преступление и наказание",
    author: "Фёдор Достоевский",
    authorId: "dostoevsky",
    genre: "Художественная литература",
    publisher: "Азбука-Аттикус",
    publisherId: "azbuka",
    price: 450,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 448,
    isbn: "978-5-389-07544-0",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389075440-L.jpg",
    description: "Один из самых значительных романов Ф.М. Достоевского."
  },
  {
    title: "Мастер и Маргарита",
    author: "Михаил Булгаков",
    authorId: "bulgakov",
    genre: "Художественная литература",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 520,
    oldPrice: 700,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2024,
    pages: 480,
    isbn: "978-5-04-101234-5",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785041012345-L.jpg",
    description: "Самый знаменитый роман Михаила Булгакова."
  },
  {
    title: "Оно",
    author: "Стивен Кинг",
    authorId: "king",
    genre: "Ужасти",
    publisher: "АСТ",
    publisherId: "ast",
    price: 780,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: true,
    year: 2024,
    pages: 1120,
    isbn: "978-5-17-123456-7",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785171234567-L.jpg",
    description: "Один из самых страшных и эпических романов Стивена Кинга."
  },
  {
    title: "Гарри Поттер и философский камень",
    author: "Дж.К. Роулинг",
    authorId: "rowling",
    genre: "Фэнтези",
    publisher: "Росмэн",
    publisherId: "eksimo",
    price: 650,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 432,
    isbn: "978-5-353-01234-5",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785353012345-L.jpg",
    description: "Первая книга легендарной серии о мальчике-волшебнике."
  },
  {
    title: "Ночной дозор",
    author: "Сергей Лукьяненко",
    authorId: "lukyanenko",
    genre: "Фэнтези",
    publisher: "АСТ",
    publisherId: "ast",
    price: 420,
    oldPrice: 560,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 480,
    isbn: "978-5-17-098765-4",
    coverUrl: "https://m.media-amazon.com/images/I/A1JI5-I2WQL._UF1000,1000_QL80_.jpg",
    description: "Первый роман культовой серии «Дозоры». В Москве существует тайное противостояние между Светом и Тьмой."
  },
  {
    title: "Generation «П»",
    author: "Виктор Пелевин",
    authorId: "pelevin",
    genre: "Художественная литература",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 380,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2022,
    pages: 352,
    isbn: "978-5-04-087654-3",
    coverUrl: "https://imo10.labirint.ru/books/496148/cover.jpg/242-0",
    description: "Роман-бестселлер Виктора Пелевина о поколении, выросшем в эпоху перемен. Главный герой — Вавилен Татарский, бывший литератор, ставший создателем рекламы."
  },
  {
    title: "1984",
    author: "Джордж Оруэлл",
    authorId: "orwell",
    genre: "Антиутопия",
    publisher: "Азбука-Аттикус",
    publisherId: "azbuka",
    price: 350,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 320,
    isbn: "978-5-389-06789-0",
    coverUrl: "https://m.media-amazon.com/images/I/810z0fZdgDL._UF1000,1000_QL80_.jpg",
    description: "Антиутопия Джорджа Оруэлла — одна из самых важных книг XX века. Мир, в котором Большой Брат следит за каждым."
  },
  {
    title: "Думай медленно... решай быстро",
    author: "Даниэль Канеман",
    authorId: "science",
    genre: "Психология",
    publisher: "АСТ",
    publisherId: "ast",
    price: 680,
    oldPrice: 850,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 656,
    isbn: "978-5-17-076543-2",
    coverUrl: "https://m.media-amazon.com/images/I/61mG3hv5S0L._UF1000,1000_QL80_.jpg",
    description: "Нобелевский лауреат Даниэль Канеман объясняет, почему мы принимаем неверные решения."
  },
  {
    title: "Sapiens: Краткая история человечества",
    author: "Юваль Ной Харари",
    authorId: "history",
    genre: "История",
    publisher: "Синдбад",
    publisherId: "piter",
    price: 750,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2024,
    pages: 512,
    isbn: "978-5-906543-21-0",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785906543210-L.jpg",
    description: "Мировой бестселлер о пути человечества от каменного века до Кремниевой долины."
  },
  {
    title: "Маленький принц",
    author: "Антуан де Сент-Экзюпери",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Росмэн",
    publisherId: "eksimo",
    price: 290,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2024,
    pages: 96,
    isbn: "978-5-353-09876-5",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785353098765-L.jpg",
    description: "Философская сказка для детей и взрослых. Маленький принц путешествует по планетам и учится понимать любовь, дружбу и ответственность."
  },
  {
    title: "Дюна",
    author: "Фрэнк Герберт",
    authorId: "sf",
    genre: "Научная фантастика",
    publisher: "АСТ",
    publisherId: "ast",
    price: 590,
    oldPrice: 780,
    rating: 5,
    reviewsCount: 1,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 704,
    isbn: "978-5-17-112233-4",
    coverUrl: "https://imo10.labirint.ru/books/741877/cover.jpg/484-0",
    description: "Величайший научно-фантастический роман всех времён. Пустынная планета Арракис — единственный источник самого ценного вещества во вселенной."
  },
  {
    title: "Атомные привычки",
    author: "Джеймс Клир",
    authorId: "psychology",
    genre: "Психология",
    publisher: "Питер",
    publisherId: "piter",
    price: 540,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "new",
    isNew: true,
    year: 2024,
    pages: 304,
    isbn: "978-5-4461-2345-6",
    coverUrl: "https://ir.ozone.ru/s3/multimedia-d/6292895509.jpg",
    description: "Как маленькие изменения приводят к большим результатам. Проверенная система формирования полезных привычек."
  },
  {
    title: "Убить пересмешника",
    author: "Харпер Ли",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Азбука-Аттикус",
    publisherId: "azbuka",
    price: 420,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 416,
    isbn: "978-5-389-05678-9",
    coverUrl: "https://mostik.de/cdn/shop/files/ubit-peresmeshnika-9785170904112-1.webp?v=1777287548&width=300",
    description: "История юриста Аттикуса Финча, защищающего чернокожего человека в расистском южному городке."
  },
  {
    title: "Думай и богатей",
    author: "Наполеон Хилл",
    authorId: "business",
    genre: "Бизнес",
    publisher: "Манн, Иванов и Фербер",
    publisherId: "machon",
    price: 480,
    oldPrice: 620,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2022,
    pages: 384,
    isbn: "978-5-00100-123-4",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785001001234-L.jpg",
    description: "Классическое пособие по достижению финансового успеха. 13 принципов достижения богатства."
  },
  {
    title: "Граф Монте-Кристо",
    author: "Александр Дюма",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 670,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 1280,
    isbn: "978-5-04-076543-2",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040765432-L.jpg",
    description: "Грандиозная история о предательстве, заточении и мести. Эдмон Дантес находит сокровища и возвращается как загадочный богач."
  },
  {
    title: "Шерлок Холмс. Полное собрание",
    author: "Артур Конан Дойл",
    authorId: "detective",
    genre: "Детективы и триллеры",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 1200,
    oldPrice: 1500,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2024,
    pages: 1152,
    isbn: "978-5-04-112233-4",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785041122334-L.jpg",
    description: "Полное собрание всех рассказов и повестей о великом сыщике Шерлоке Холмсе."
  },
  {
    title: "Три товарища",
    author: "Эрих Мария Ремарк",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Азбука-Аттикус",
    publisherId: "azbuka",
    price: 390,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 480,
    isbn: "978-5-389-04567-8",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389045678-L.jpg",
    description: "Роман о дружбе, любви и потерянном поколении. Три друга, прошедшие Первую мировую войну."
  },
  {
    title: "Портрет Дориана Грея",
    author: "Оскар Уайльд",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Азбука-Аттикус",
    publisherId: "azbuka",
    price: 320,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "new",
    isNew: true,
    year: 2024,
    pages: 256,
    isbn: "978-5-389-08901-2",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389089012-L.jpg",
    description: "Единственный роман Оскара Уайльда — история о прекрасном юноше, который загадывает остаться вечно молодым."
  },
  {
    title: "Цветы для Элджернона",
    author: "Дэниел Киз",
    authorId: "sf",
    genre: "Научная фантастика",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 360,
    oldPrice: 450,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 320,
    isbn: "978-5-04-065432-1",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040654321-L.jpg",
    description: "Пронзительная история умственно отсталого уборщика, который в результате эксперимента становится гением."
  },
  {
    title: "Тёмные начала",
    author: "Филип Пулман",
    authorId: "fantasy",
    genre: "Фэнтези",
    publisher: "АСТ",
    publisherId: "ast",
    price: 950,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "new",
    isNew: true,
    year: 2024,
    pages: 1100,
    isbn: "978-5-17-123789-0",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785171237890-L.jpg",
    description: "Захватывающая трилогия о приключениях Лиры Белаквы в параллельных мирах."
  },
  {
    title: "Шантарам",
    author: "Грегори Дэвид Робертс",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Азбука",
    publisherId: "azbuka",
    price: 720,
    oldPrice: 900,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 864,
    isbn: "978-5-389-01234-5",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389012345-L.jpg",
    description: "Исповедь человека, который сумел выбраться из бездны и найти смысл жизни в далекой Индии."
  },
  {
    title: "Богатый папа, бедный папа",
    author: "Роберт Кийосаки",
    authorId: "business",
    genre: "Бизнес",
    publisher: "Попурри",
    publisherId: "machon",
    price: 450,
    oldPrice: null,
    rating: 5,
    reviewsCount: 1,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 352,
    isbn: "978-985-15-4321-0",
    coverUrl: "https://m.media-amazon.com/images/I/71m9fX5HlkL._UF1000,1000_QL80_.jpg",
    description: "Книга, которая перевернет ваше представление о деньгах и инвестировании."
  },
  {
    title: "Ведьмак. Последнее желание",
    author: "Анджей Сапковский",
    authorId: "fantasy",
    genre: "Фэнтези",
    publisher: "АСТ",
    publisherId: "ast",
    price: 580,
    oldPrice: 750,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 320,
    isbn: "978-5-17-087654-2",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785170876542-L.jpg",
    description: "Первая книга о приключениях Геральта из Ривии, профессионального охотника на монстров."
  },
  {
    title: "Марсианин",
    author: "Энди Вейер",
    authorId: "sf",
    genre: "Научная фантастика",
    publisher: "АСТ",
    publisherId: "ast",
    price: 490,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2022,
    pages: 384,
    isbn: "978-5-17-091234-8",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785170912348-L.jpg",
    description: "Захватывающая история выживания астронавта Марка Уотни, случайно оставленного на Марсе."
  },
  {
    title: "Алхимик",
    author: "Пауло Коэльо",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "АСТ",
    publisherId: "ast",
    price: 340,
    oldPrice: null,
    rating: 5,
    reviewsCount: 1,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 224,
    isbn: "978-5-17-012345-0",
    coverUrl: "https://booqua.de/images/product_gallery/221724436122_583689.jpg",
    description: "Притча о пастухе Сантьяго, который отправился на поиски сокровищ и нашел свой Путь."
  },
  {
    title: "Гордость и предубеждение",
    author: "Джейн Остин",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Азбука",
    publisherId: "azbuka",
    price: 380,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2022,
    pages: 416,
    isbn: "978-5-389-01234-9",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389012349-L.jpg",
    description: "Классический роман о нравах, любви и предрассудках в английском обществе."
  },
  {
    title: "Рассказ Служанки",
    author: "Маргарет Этвуд",
    authorId: "fiction",
    genre: "Антиутопия",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 460,
    oldPrice: 600,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 352,
    isbn: "978-5-04-098765-1",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040987651-L.jpg",
    description: "Пугающая антиутопия о мире, где женщины лишены всех прав."
  },
  {
    title: "Чертоги разума",
    author: "Андрей Курпатов",
    authorId: "psychology",
    genre: "Психология",
    publisher: "Капитал",
    publisherId: "piter",
    price: 890,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "new",
    isNew: true,
    year: 2024,
    pages: 416,
    isbn: "978-5-907123-45-6",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785907123456-L.jpg",
    description: "Как научить мозг работать эффективно в эпоху цифровой зависимости."
  },
  {
    title: "Крестный отец",
    author: "Марио Пьюзо",
    authorId: "fiction",
    genre: "Детективы и триллеры",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 520,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 576,
    isbn: "978-5-04-012345-8",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040123458-L.jpg",
    description: "Эпическая сага о жизни и делах мафиозного клана Корлеоне."
  },
  {
    title: "Норвежский лес",
    author: "Харуки Мураками",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 440,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2022,
    pages: 480,
    isbn: "978-5-04-087651-2",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040876512-L.jpg",
    description: "Роман о взрослении, потерях и поисках любви в Токио 1960-х годов."
  },
  {
    title: "Зеленая миля",
    author: "Стивен Кинг",
    authorId: "king",
    genre: "Ужасти",
    publisher: "АСТ",
    publisherId: "ast",
    price: 550,
    oldPrice: 700,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2023,
    pages: 480,
    isbn: "978-5-17-098123-4",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785170981234-L.jpg",
    description: "Потрясающая история о чудесах в блоке смертников тюрьмы «Холодная гора»."
  },
  {
    title: "Заводной апельсин",
    author: "Энтони Бёрджесс",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "Азбука",
    publisherId: "azbuka",
    price: 320,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 256,
    isbn: "978-5-389-01111-2",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389011112-L.jpg",
    description: "Провокационный роман о подростковой жестокости и попытках государства исправить человека."
  },
  {
    title: "Пролетая над гнездом кукушки",
    author: "Кен Кизи",
    authorId: "fiction",
    genre: "Художественная литература",
    publisher: "ЭКСМО",
    publisherId: "eksimo",
    price: 410,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: false,
    year: 2023,
    pages: 384,
    isbn: "978-5-04-022222-3",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785040222223-L.jpg",
    description: "История бунтаря Макмерфи в психиатрической клинике, управляемой жесткой Старшей сестрой."
  },
  {
    title: "Шерлок Холмс. Полное собрание",
    author: "Артур Конан Дойл",
    authorId: "doyle",
    genre: "Детективы и триллеры",
    publisher: "Азбука",
    publisherId: "azbuka",
    price: 1200,
    oldPrice: 1500,
    rating: 0,
    reviewsCount: 0,
    badge: "sale",
    isNew: false,
    year: 2022,
    pages: 1152,
    isbn: "978-5-389-01234-6",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389062563-L.jpg",
    description: "Все рассказы и повести о великом сыщике под одной обложкой."
  },
  {
    title: "1984",
    author: "Джордж Оруэлл",
    authorId: "orwell",
    genre: "Антиутопия",
    publisher: "Азбука-Аттикус",
    publisherId: "azbuka",
    price: 380,
    oldPrice: null,
    rating: 0,
    reviewsCount: 0,
    badge: null,
    isNew: false,
    year: 2023,
    pages: 320,
    isbn: "978-5-389-12345-6",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785389025629-L.jpg",
    description: "Самый известный роман-антиутопия в мировой литературе."
  },
  {
    title: "Атомные привычки",
    author: "Джеймс Клир",
    authorId: "clear",
    genre: "Психология",
    publisher: "Питер",
    publisherId: "piter",
    price: 690,
    oldPrice: 850,
    rating: 0,
    reviewsCount: 0,
    badge: "bestseller",
    isNew: true,
    year: 2024,
    pages: 320,
    isbn: "978-5-4461-1234-5",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9785446112345-L.jpg",
    description: "Простой и проверенный способ сформировать хорошие привычки и избавиться от плохих."
  }
];

async function seed() {
    try {
        const categories = [...new Set(booksData.map(b => b.genre))];
        for (const catName of categories) {
            await Category.findOrCreate({ where: { name: catName } });
        }

        const allCats = await Category.findAll();
        const catMap = {};
        allCats.forEach(c => catMap[c.name] = c.id);

        for (const book of booksData) {
            const { genre, ...bookInfo } = book;
            await Book.findOrCreate({
                where: { isbn: book.isbn },
                defaults: { ...bookInfo, categoryId: catMap[genre] }
            });
        }

        console.log('Seed completed successfully');
    } catch (err) {
        console.error('Seed error:', err);
    }
}

module.exports = function() {
  return booksData;
};
